package com.studyexchange.core;

public enum UserState {
    REQUEST_NAME,
    REQUEST_GRADE,
    REQUEST_SUBJECTS_CAN_HELP_WITH_EDUCATIONAL,
    REQUEST_HELP_EDUCATIONAL,
    FILL_HELP_DESCRIPTION_EDUCATIONAL,
    FILL_HELP_PHOTOS_EDUCATIONAL,
    READY_TO_SEARCH_EDUCATIONAL,
    APPLY_FILTERS_START_SEARCHING
}
