package com.studyexchange.core;

public enum UserState {
    NO_NAME_INTRO,
    NO_GRADE,
    REQUEST_HELP_EDUCATIONAL,
    FILL_HELP_DESCRIPTION_EDUCATIONAL,
    FILL_HELP_PHOTOS_EDUCATIONAL,
    FILL_TOPICS_CAN_HELP_EDUCATIONAL,
    READY_TO_SEARCH_EDUCATIONAL,
    SEARCHING
}
